请求时添加withCredentials属性
dcmjs-org/dicomweb-client pull request #33
Opened 2021-04-25 09:20 UTC by aadelina

2021-04-25 09:30 UTC, aadelina commented
在用到开源项目时候，项目需要有涉及权限部分，请求接口时候，需要携带cookie请求，设置withCredentials属性

2021-04-25 14:12 UTC, pieper commented
> 在用到开源项目时候，项目需要有涉及权限部分，请求接口时候，需要携带cookie请求，设置withCredentials属性

Google translate reads this as:
"When using an open source project, the project needs to have a permission part. When requesting an interface, it needs to carry a cookie request and set the withCredentials attribute"

MDN says: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

I don't have any experience with this but it seems like something useful.  Does anyone see any issues?  @emelalkim ?  @hackermd ?

2021-04-25 14:12 UTC, pieper requested changes

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +    let withCredentials
Needs a semicolon

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
semicolon

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
semicolon

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
semicolon

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
semicolon

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
semicolon

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
semicolon

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
;

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
;

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
;

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
;

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
;

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
;

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +    let withCredentials
it would probably be better to explicitly initialize these to false rather than leaving them undefined, just stylistically.

2021-04-25 14:12 UTC, pieper commented on src/api.js
> +        withCredentials = options.withCredentials
I flagged a bunch of these, but not all.  They aren't syntax errors but we use semicolons to be consistent with common style.

2021-04-26 02:31 UTC, aadelina commented
OK, I'll add the semicolon and optimize it

2021-04-28 21:17 UTC, emelalkim commented
> > 在用到开源项目时候，项目需要有涉及权限部分，请求接口时候，需要携带cookie请求，设置withCredentials属性
> 
> Google translate reads this as:
> "When using an open source project, the project needs to have a permission part. When requesting an interface, it needs to carry a cookie request and set the withCredentials attribute"
> 
> MDN says: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials
> 
> I don't have any experience with this but it seems like something useful. Does anyone see any issues? @emelalkim ? @hackermd ?

Hi,
As far as I see from the code, it is for the requests that are sent to dicomweb server, right? Neither our dicomweb server or ePAD support or use cookie based authentication. I am not sure if there are dicomweb servers that do. I did a quick check and Ortanc supports adding these extra headers. I do not see any harm in doing so but @hackermd should have a better idea.

2021-05-07 14:15 UTC, pieper commented
@hackermd what do you think?  It would be great to harmonize the features and interfaces of the python and javascript implementations if we can.

2021-05-07 17:11 UTC, hackermd commented
> @hackermd what do you think? It would be great to harmonize the features and interfaces of the python and javascript implementations if we can

I don't have a lot of experience with cookies and cross-origin requests. I don't think there would be a direct equivalent in Python or whether there would be a need to support cross-origin requests in Python at all.

2021-05-07 18:27 UTC, pieper commented
> I don't have a lot of experience with cookies and cross-origin requests. I don't think there would be a direct equivalent in Python am not sure whether there would be a need to support cross-origin requests in Python at all.

Good point, those two wouldn't come up in the python case.

So I guess on the whole this adds utility for a valid use case and doesn't raise any concerns that something else will break, so I'll go ahead and merge.

2021-05-07 18:28 UTC, merged