fix(dicomweb-client):Make the retrieveBulkData handle either single or multipart responses.
dcmjs-org/dicomweb-client pull request #48
Opened 2021-11-17 17:53 UTC by wayfarer3130

The DICOMweb standard can be interpreted in a few ways, one of which is that BulkDataURI always returns single part bulk data when requested as a full URL.  This interpretation doesn't work for the existing retrieveBulkDataURI, so the library has been updated to allow retrieving as either single or multipart, letting the server decide how to return the data.

2021-11-17 17:54 UTC, wayfarer3130 commented on .babelrc
> +  "plugins": ["@babel/plugin-proposal-class-properties"],
I'd had a change initially with a class property  - useful to have, but I can remove this if desired.

2021-11-17 17:55 UTC, wayfarer3130 commented on src/api.js
> +            if( request.responseType=='arraybuffer' ) {
This was the least breaking change I could figure out.

2021-11-17 17:56 UTC, wayfarer3130 commented on src/api.js
> +  _handleRelativeURI(options = {}, uri) {
This doesn't impact non-relative URIs, but allows the URI to be relative, something that is being defined in an upcoming supplement, but is already implemented in a few places.

2021-11-17 17:58 UTC, wayfarer3130 commented on src/api.js
> +    const withCredentials = options.withCredentials || false;
Just a shorter form of the if statement.

2021-11-18 23:20 UTC, hackermd requested changes
A couple of comments regarding coding style and other minor things.

The main question remains whether it would be good idea to allow both multipart and single part messages. If this is indeed what the standard now states (or will be stating), then we should improve the specification of the `Accept` field and the handling of the response payload. We should avoid requesting resources with `Accept: multipart/related; type=application/octet-stream` and then expecting `Content-Type: application/octet-stream`.

2021-11-18 23:20 UTC, hackermd commented on src/api.js
> +    const { BulkDataURI, mediaTypes, byteRange, multipart=true } = options;
I may have to take back https://github.com/dcmjs-org/dicomweb-client/issues/47#issuecomment-973338241.

The user shouldn't have to specify whether the response should be multipart or not. It would also be weird to request data with `Accept: multipart/related; type=application/octet-stream, application/octet-stream`.

2021-11-18 23:20 UTC, hackermd commented on src/message.js
> +  if( contentType && contentType.indexOf('multipart')==-1 ) {
This hack indicates that the approach is problematic..

Either way this statement should not be in `multipartDecode()`. The function should receive a multipart message. If the message is not multipart, this function should not be called.

2022-03-09 22:04 UTC, wayfarer3130 commented on src/api.js
> +
It isn't necessary to specify the accept at all, in which case it might come back in either of the formats, and as you state later, if you have them both equally prioritized, then either one can come back, so I'd like to just leave the handling.

2022-03-09 22:13 UTC, wayfarer3130 commented on src/api.js
> +    const { BulkDataURI, mediaTypes, byteRange, multipart=true } = options;
Agreed, this should be an overall configuration option instead.

2022-03-10 13:46 UTC, hackermd commented on src/api.js
> +    const { BulkDataURI, mediaTypes, byteRange, multipart=true } = options;
I would really like to avoid global configuration.

2022-03-10 13:48 UTC, hackermd commented
The `"Value"` field of a DICOM JSON representation of a Data Element is an array (see [F.2.2 DICOM JSON Model Object Structure](https://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_F.2.2.html) and [F.2.4 DICOM JSON Value Multiplicity](https://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_F.2.4.html)). If the object contains the `"BulkDataURI"` instead of the `"Value"` field, then it would also make sense for the response message to the bulkdata retrieve request to be multipart.

2022-03-10 13:50 UTC, hackermd commented
While the standard may also support singlepart messages, an origin server would still have to support multipart messages. Therefore, I don't see why the behavior of the client has to change.

2022-03-10 19:14 UTC, hackermd commented on src/api.js
> +  _handleRelativeURI(options = {}, uri) {
@pieper @dclunie this will be pertinent to the handling of data from multiple servers, because it will no longer be obvious from where the bulkdata will need to be retrieved. We will then need to keep track of the mapping between metadata responses and origin servers.

2022-03-10 22:49 UTC, wayfarer3130 commented on src/api.js
> +import { multipartEncode, multipartDecode } from './message.js';
I ran lint and it auto-fixed things.  Didn't notice immediately.  @hackermd would it be possible to run lint on master, and then commit that, so as to not see so many differences?

2022-03-10 22:51 UTC, wayfarer3130 commented on src/api.js
> +   * @param {boolean|String} options.singlepart - retrieve singlepart for the named types.
I added an option singlepart to specify what can be retrieved via singlepart.  This is global for the web client, but allows one to specify up to three options, of which the only one implemented so far is bulkdata.

2022-03-10 22:52 UTC, wayfarer3130 commented on src/api.js
> +    if (options.singlepart) {
The default is to set singlepart to an empty string to mean nothing, so just checking options.singlepart works effectively here.

2022-03-10 22:53 UTC, wayfarer3130 commented on src/api.js
> +            const contentType = request.getResponseHeader('Content-Type');
I moved the multipart decoding into the http retrieve handler itself.  That way it can decide whether or not the decode is required based on what comes back from the request.

2022-03-10 22:55 UTC, wayfarer3130 commented on src/api.js
> -    return this._httpGet(url, headers, "arraybuffer", progressCallback, withCredentials).then(
This is an example get, where there is just a non-false value passed to indicate to decode.

2022-03-10 23:05 UTC, wayfarer3130 commented on src/api.js
> +   * @param {string} studyUid to use in the full URL
Changed the signature as requested.

2022-03-10 23:09 UTC, wayfarer3130 commented on src/api.js
> +  _handleRelativeURI(options = {}, uri) {
In the case of multi-server responses, it is still perfectly fine to return a full URL, and that probably makes sense for multi-server responses.

2022-03-10 23:11 UTC, wayfarer3130 commented on src/api.js
> +    const { BulkDataURI, mediaTypes, byteRange, multipart=true } = options;
I did make it global, but set it up as a multi-valued field to allow specifying what response types are single part.
However, as you pointed out,  it is possible to request both single and multipart and have either one come back.  For a webserver that doesn't actually interpret the accept header, it may not even know how it comes back.

2022-03-10 23:12 UTC, wayfarer3130 commented on src/message.js
> +  if( contentType && contentType.indexOf('multipart')==-1 ) {
Changed this as requested to have the get method decide, so it returns a consistent result type.

2022-03-11 11:32 UTC, dclunie commented on src/api.js
> +  _handleRelativeURI(options = {}, uri) {
On absolute or relative BulkDataURIs ...

The BulkDataURI used in WADO-RS responses is always an http URL, but where does it say in PS3.18 or PS3.19 that it can be "relative" rather than "absolute", and if so where, is it defined what it is "relative" to?

Looking through Sup 161, Sup 166, CP 1351, Sup 183, and CP2040, I don't see that this URI has ever been described (now or in the past) as anything other than:

[PS3.18 F.2.2](https://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_F.2.2.html) ... "BulkDataURI: A string encoding the WADO-RS URL of a bulk data item" (since Sup 166)

[PS3.18 F.2.6](https://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_F.2.6.html) BulkDataURI ... "this contains the URI of a bulk data element as defined in ..." (since Sup 166)

[PS3.19 Table A.1.5-2](https://dicom.nema.org/medical/dicom/current/output/chtml/part19/chapter_A.html#para_fd94e2a5-822b-461a-b434-ddaf24a0fad4) "The HTTP(S) URI for this bulk data reference" (since Sup 161)

For once, Sup 183 did not seem to screw with this and make it worse (or better), though it did add a definition:
[3.9 Web Services Definitions Bulk Data URI](https://dicom.nema.org/medical/dicom/current/output/chtml/part18/chapter_3.html#glossentry_BulkDataURI) "A Uniform Resource Identifier that references Bulkdata"

@wayfarer3130, if you are referring to Sup 211 DICOMweb application/ZIP Payload as the "upcoming supplement", (a) I thought you had given up on that supplement and it is dead, and (b) it only describes file: protocol relative URLs for use inside the zip packaging, and does not affect http URLs (at least as I read the last draft sup211_zip_archive-2021-10-01.docx); if you are going to resurrect it, we need to remember to make the PS3.19 Table A.1.5-2 changes http: or file: protocol specific (or define this wherever it is used), and not suddenly allow just any protocol to be used anywhere.

2022-03-11 13:31 UTC, wayfarer3130 commented on src/api.js
> +  _handleRelativeURI(options = {}, uri) {
@dclunie - the original comment was with respect to application/zip, which I agree is dead (comment was originally made about 4 months ago in February).  
However, none of the definitions actually prohibit relative URIs - the referenced standard specifically states:
"A Uniform Resource Identifier (URI) is a compact sequence of
   characters that identifies an abstract or physical resource.  This
   specification defines the generic URI syntax and a process for
   resolving URI references that might be in relative form"

so I have to believe it is permitted already in part 18.
 
A serverless/protocol free relative URI is certainly well defined, and is handled by the code included (eg /dicomweb/studies/1.2.3/bulkdata/ab is well defined)
A study root metadata (eg .../studies/1.2.3/metadata) relative URI is also well defined according to standard, and is handled by the code based on RFC 3986 # 5.1.3  (eg  bulkdata/ab is well defined relative to studies/1.2.3/metadata)
That leaves just the relative URI for series/instance level metadata.  If those are considered simply parts of the root metadata, then they can be handled the same as the previous case - however, I think it would be best to add a definition into the standard according to RFC 3986 #5.1.4 that defines the default root URI as being the same as that for the study level metadata, eg .../studies/<studyUID>/ as the root, although I'd be agreeable to either the qido root (eg /dicomweb/ in many cases), or the studies root, but the disadvantage of either of those being that it changes the existing behaviour as defined in part 18/19.

2022-04-06 21:48 UTC, wayfarer3130 commented on src/api.js
> +            // Automatically distinguishes between multipart and singlepart in an array buffer, and
Make it return a consistent type - in this case, an array of buffer data, just decide on how to break that up at retrieve time.

2022-04-06 21:49 UTC, wayfarer3130 commented on src/api.js
> +    return this._httpGet(url, headers, 'arraybuffer', progressCallback, withCredentials);
This makes the http get consistent and it doesn't need the explicit multipart decode.

2022-04-06 21:49 UTC, wayfarer3130 commented on src/api.js
> +    if (this.singlepart.indexOf('bulkdata') !== -1) {
This just does the call without an accept, handling whatever is returned, either single or multipart in the normal way.

2022-04-07 12:10 UTC, wayfarer3130 commented
CP 2204 available at https://docs.google.com/document/d/1UbAZFAyTF8p7Vf_q_lR9mex82Zkr7zB-/edit?usp=sharing&ouid=106394421000961430700&rtpof=true&sd=true
specifies the single part retrieve that is setup here.

2022-04-11 21:20 UTC, hackermd commented
> CP 2204 available at https://docs.google.com/document/d/1UbAZFAyTF8p7Vf_q_lR9mex82Zkr7zB-/edit?usp=sharing&ouid=106394421000961430700&rtpof=true&sd=true specifies the single part retrieve that is setup here.

Thanks @wayfarer3130 for sharing the draft of the CP.

[Section 10.4.3.3.5](https://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_10.4.3.3.5) states:

> The payload for a Bulkdata Resource (see [Section 10.4.1.1.5](https://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_10.4.1.1.5)) shall contain all the bulkdata for the resource. When the resource is a single Bulkdata URI, the payload will contain the single corresponding element. When the resource is a Study, Series or Instance Bulkdata resource, the payload will contain all the bulkdata of the corresponding instance(s). Bulkdata in a multipart response shall have a Content-Location header field that corresponds to the URI contained in the corresponding Element in the Metadata.

The wording is indeed confusing and should be improved in my opinion. I think the confusion is primarily due to the fact that the term "bulkdata" is used to refer to two different things:

1. Bulkdata resources that can be accessed via the DICOMweb API at the `/bulkdata` endpoints. In this case, a resource represents a collection of DICOM Data Elements.
2. Bulkdata values that can be accessed via a Bulkdata URI that's included in a JSON metadata resource. In this case, a resource represents the value of an individual DICOM Data Element.

[Table 10.4.4-1](https://dicom.nema.org/medical/dicom/current/output/html/part18.html#para_00ff33f6-cd54-4b7a-bd96-38fb4efe8656) explicitly requires the media type of any bulkdata resource to be `multipart/related; type="application/octet-stream"`.
For (1), it has to be multi-part because a study, series, and instance may contain more than one bulkdata element. Since an element may have a value multiplicity greater than one and values in JSON metadata are arrays, I tend argue that the payload of the response messages shall also be multi-part for (2). In general, the client may not know whether the value is single or multi-part.

2022-04-12 12:01 UTC, wayfarer3130 commented
@hackermd - the problem with things like:
[Table 10.4.4-1](https://dicom.nema.org/medical/dicom/current/output/html/part18.html#para_00ff33f6-cd54-4b7a-bd96-38fb4efe8656) explicitly requires the media type of any bulkdata resource to be multipart/related; type="application/octet-stream".
is that they aren't definitive because there are other tables that allow it like: 
https://dicom.nema.org/medical/dicom/current/output/html/part18.html#table_8.7.3-4
as well as other places that suggest that it is required to support single part bulkdatauri requests.

The general approach of the DICOM standards committee to things that have been allowed by the standard, such as both the relative URI and single part bulkdata is to try to clarify how it is used, but not restrict things that were previously allowed under a reasonable reading of the standard.

Returning single part is extremely useful for anything that does a direct render like PDF, video, audio etc, and having the dcmjs library able to deal with either type is useful for when one sometimes wants to retrieve things for direct render and sometimes does background retrieves.   In theory, the implementation on the DICOMweb side has to handle both, but implementations such as the static wado that stores the data in the expected final format, compressed, are far faster when they don't need to wrap and uncompress the data.

2022-04-12 12:53 UTC, hackermd commented
> Returning single part is extremely useful for anything that does a direct render like PDF, video, audio etc

Rendered resources (endpoint `/rendered`) have always been single-part!

2022-06-20 16:02 UTC, wayfarer3130 commented
> The `"Value"` field of a DICOM JSON representation of a Data Element is an array (see [F.2.2 DICOM JSON Model Object Structure](https://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_F.2.2.html) and [F.2.4 DICOM JSON Value Multiplicity](https://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_F.2.4.html)). If the object contains the `"BulkDataURI"` instead of the `"Value"` field, then it would also make sense for the response message to the bulkdata retrieve request to be multipart.

That is a misunderstanding of the multiplicity and the binary representation - the BulkDataURI refers to a single object that contains the entire Value, all of the various parts in however many bytes plus multiplicity of values it contains.  That is, if one has the value:
CT\MR
Then the literal bulk data URI value would be  "CT\MR "  (zero character at end for padding), without multiple values etc.

2022-06-20 16:02 UTC, closed without merging

2022-06-20 17:08 UTC, hackermd commented
> That is a misunderstanding of the multiplicity and the binary representation - the BulkDataURI refers to a single object that contains the entire Value, all of the various parts in however many bytes plus multiplicity of values it contains.

The BulkDataURI does not point to a single *object*, but to a single *resource*, which is defined to be a multi-part message.

I think you are right about the fact that values of a data element with value multiplicity greater than one would in principle be encoded in one message part:
https://dicom.nema.org/medical/dicom/current/output/chtml/part19/chapter_A.html#para_2b996d78-0885-405e-a398-275654546c4b

However, data elements with a binary value representation (or large text) generally have a value multiplicity of 1 anyways.

The main reason the messages are multi-part is probably because the Pixel Data element may have multiple frames (and frame fragments). Each frame would need to be encoded as a separate message part.

2023-05-31 01:31 UTC, igoroctaviano commented
> > That is a misunderstanding of the multiplicity and the binary representation - the BulkDataURI refers to a single object that contains the entire Value, all of the various parts in however many bytes plus multiplicity of values it contains.
> 
> The BulkDataURI does not point to a single _object_, but to a single _resource_, which is defined to be a multi-part message.
> 
> I think you are right about the fact that values of a data element with value multiplicity greater than one would in principle be encoded in one message part: https://dicom.nema.org/medical/dicom/current/output/chtml/part19/chapter_A.html#para_2b996d78-0885-405e-a398-275654546c4b
> 
> However, data elements with a binary value representation (or large text) generally have a value multiplicity of 1 anyways.
> 
> The main reason the messages are multi-part is probably because the Pixel Data element may have multiple frames (and frame fragments). Each frame would need to be encoded as a separate message part.

@hackermd Now that there is an actual change to the DICOM standard to support being able to fetch using either method, what's left to merge this change? I'll also need this change for a different project and I want to help to get this merged.

2023-05-31 11:41 UTC, wayfarer3130 commented
> > > That is a misunderstanding of the multiplicity and the binary representation - the BulkDataURI refers to a single object that contains the entire Value, all of the various parts in however many bytes plus multiplicity of values it contains.
> > 
> > 
> > The BulkDataURI does not point to a single _object_, but to a single _resource_, which is defined to be a multi-part message.
> > I think you are right about the fact that values of a data element with value multiplicity greater than one would in principle be encoded in one message part: https://dicom.nema.org/medical/dicom/current/output/chtml/part19/chapter_A.html#para_2b996d78-0885-405e-a398-275654546c4b
> > However, data elements with a binary value representation (or large text) generally have a value multiplicity of 1 anyways.
> > The main reason the messages are multi-part is probably because the Pixel Data element may have multiple frames (and frame fragments). Each frame would need to be encoded as a separate message part.
> 
> @hackermd Now that there is an actual change to the DICOM standard to support being able to fetch using either method, what's left to merge this change? I'll also need this change for a different project and I want to help to get this merged.

I updated the build to current.  At this point it is mostly cleanup so that the handling of multipart and singlepart is based on the actual response type rather than having a decode step multiple places.

2023-06-08 20:36 UTC, igoroctaviano commented
@pieper @swederik are you guys able to help review/approve this PR? not sure about Markus's availability nowadays.

2023-06-08 21:27 UTC, pieper commented
> @pieper @swederik are you guys able to help review/approve this PR? not sure about Markus's availability nowadays.

I read through this but did not test it.  If you are okay with the change and nobody else objects I'm fine with merging.

2023-07-25 11:51 UTC, igoroctaviano commented
LGTM 🏅 
If possible I would like to know if @dclunie has any objections based on previous discussions otherwise I would like to have this merged.

2023-07-25 21:56 UTC, igoroctaviano commented
> I have no objections.
> 
> The [final text of CP 2204](https://dicom.nema.org/medical/dicom/Final/cp2204_ft_SinglePartBulkData.pdf) which amended the [section describing the Media Types](https://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_10.4.4.html), including those for the Bulk Data Resources, should now make it clear that the origin server can return either therefore the client has to support both possibilities, making this PR necessary.
> 
> Having said that, I would have been OK with making the client more robust anyway, in the sense of the ["Postel principle" (write perfect, read anything)](https://en.wikipedia.org/wiki/Robustness_principle).

@pieper based on this reply + my testing I think we can merge this one.

2023-07-27 17:27 UTC, pieper commented
@hackermd still has one pending request that's possibly been addressed.  Since it sounds like this is an improvement I'll merge it and we can open new issues for anything not yet resolved.

2023-07-27 17:50 UTC, igoroctaviano commented
@pieper do we have to manually publish the new version or it's should be triggered by a semantic commit?

2023-07-28 01:31 UTC, pieper commented
I think @dannyrb only set up the automatic publishing for dcmjs but not this repo.  Maybe somebody who is good with these things could help automate?

2023-07-28 14:31 UTC, pieper commented
Hmm, I'm not sure either.  To my quick review all the commit messages look good: https://github.com/dcmjs-org/dicomweb-client/commits/master

2023-07-29 18:08 UTC, igoroctaviano commented
> Hmm, I'm not sure either. To my quick review all the commit messages look good: https://github.com/dcmjs-org/dicomweb-client/commits/master

You are right, the squashed commit looks fine. The last published package is from April 24 though. I don't have enough permissions to take a look myself but maybe there's something wrong with the npm account? or the commit-analyzer? (the publish last action said that there were no relevant changes, skipping the version bump)

2023-08-10 19:51 UTC, pieper commented
@igoroctaviano Hmm, I guess whatever it was got fixed since that doc ts change resulted in a new release.  🤷